image: dtzar/helm-kubectl:latest

stages:
  - upload

upload:
  stage: upload
  only:
    - main
  script:
    - export CHART_VERSION=$(helm show chart ./chart/go-redis | grep ^version|cut -d\  -f2)
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@go-redis-${CHART_VERSION}.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/go-redis/charts"'
